name: Auto Assign PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run assign reviewers script
        uses: actions/github-script@v6
        env:
          COLLABORATORS: ${{ secrets.COLLABORATORS }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./scripts/assign-reviewers.cjs');
            await script({ github, context, core });
